# Generated by Django 5.1.1 on 2024-10-04 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_product_review_delete_film_order_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
